### ISSUE TITLE
import statement fails

### ISSUE THREAD

**Issue by selfagency** [jlopezxs/express-inline-css#7]
the initial import statement fails and i'm wondering if you mean require because this is node middleware, not a browser app and it requires babel as a dependency to use es6 syntax.

```
  >> /Users/daniel/Dev/nylon-web/node_modules/express-inline-css/src/index.js:1
  >> (function (exports, require, module, __filename, __dirname) { import flatten from 'lodash.flatten'
  >> ^^^^^^
  >> SyntaxError: Unexpected token import
  >> at createScript (vm.js:56:10)
  >> at Object.runInThisContext (vm.js:97:10)
  >> at Module._compile (module.js:542:28)
  >> at Object.Module._extensions..js (module.js:579:10)
  >> at Module.load (module.js:487:32)
  >> at tryModuleLoad (module.js:446:12)
  >> at Function.Module._load (module.js:438:3)
  >> at Module.require (module.js:497:17)
  >> at require (internal/module.js:20:19)
  >> at Object.<anonymous> (/Users/daniel/Dev/nylon-web/node_modules/express-inline-css/index.js:1:80)
  >> at Module._compile (module.js:570:32)
  >> at Object.Module._extensions..js (module.js:579:10)
  >> at Module.load (module.js:487:32)
  >> at tryModuleLoad (module.js:446:12)
  >> at Function.Module._load (module.js:438:3)
  >> at Module.require (module.js:497:17)
  >> at require (internal/module.js:20:19)
  >> at Object.<anonymous> (/Users/daniel/Dev/nylon-web/src/app/core/server.js:5:20)
  >> at Module._compile (module.js:570:32)
  >> at Object.Module._extensions..js (module.js:579:10)
  >> at Module.load (module.js:487:32)
  >> at tryModuleLoad (module.js:446:12)
  >> at Function.Module._load (module.js:438:3)
  >> at Module.require (module.js:497:17)
  >> at require (internal/module.js:20:19)
  >> at Object.<anonymous> (/Users/daniel/Dev/nylon-web/src/app/nylon.js:12:18)
  >> at Module._compile (module.js:570:32)
  >> at Object.Module._extensions..js (module.js:579:10)
  >> at Module.load (module.js:487:32)
  >> at tryModuleLoad (module.js:446:12)
  >> at Function.Module._load (module.js:438:3)
  >> at Module.require (module.js:497:17)
  >> at require (internal/module.js:20:19)
  >> at Object.<anonymous> (/Users/daniel/Dev/nylon-web/app.js:7:20)
  >> at Module._compile (module.js:570:32)
  >> at Object.Module._extensions..js (module.js:579:10)
  >> at Module.load (module.js:487:32)
  >> at tryModuleLoad (module.js:446:12)
  >> at Function.Module._load (module.js:438:3)
  >> at Module.runMain (module.js:604:10)
  >> at run (bootstrap_node.js:393:7)
  >> at startup (bootstrap_node.js:150:9)
  >> at bootstrap_node.js:508:3
  [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by selfagency** [comment]
resolved in #8
